name: z_example
description: Example usage of package:z.
version: 0.1.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  z:
    path: ../

flutter:
  uses-material-design: true
